// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/release-impact/Comparison.tsx": () => import("../components/mockups/release-impact/Comparison.tsx"),
  "./components/mockups/release-impact/TrackDetail.tsx": () => import("../components/mockups/release-impact/TrackDetail.tsx"),
  "./components/mockups/release-impact/TrackList.tsx": () => import("../components/mockups/release-impact/TrackList.tsx"),
  "./components/mockups/title-fonts/CormorantGaramond.tsx": () => import("../components/mockups/title-fonts/CormorantGaramond.tsx"),
  "./components/mockups/title-fonts/JosefinSans.tsx": () => import("../components/mockups/title-fonts/JosefinSans.tsx"),
  "./components/mockups/title-fonts/KleeOne.tsx": () => import("../components/mockups/title-fonts/KleeOne.tsx"),
  "./components/mockups/title-fonts/ShipporiMincho.tsx": () => import("../components/mockups/title-fonts/ShipporiMincho.tsx"),
  "./components/mockups/title-fonts/System.tsx": () => import("../components/mockups/title-fonts/System.tsx")
};
